/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001b3e",
        "on-primary-container": "#848484",
        "secondary-fixed-dim": "#ffb595",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-primary": "#c6c6c6",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d7e3ff",
        "surface-tint": "#5e5e5e",
        "surface-container": "#eeeef0",
        "outline-variant": "#cfc4c5",
        "surface-container-highest": "#e2e2e4",
        "surface-container-high": "#e8e8ea",
        "secondary-container": "#fe7a37",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#632300",
        surface: "#f9f9fb",
        "on-primary": "#ffffff",
        "tertiary-container": "#001b3e",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed-variant": "#7c2e00",
        "on-primary-fixed": "#1b1b1b",
        "inverse-on-surface": "#f0f0f2",
        "tertiary-fixed-dim": "#aac7ff",
        secondary: "#a23f00",
        "surface-container-low": "#f3f3f5",
        "on-tertiary-container": "#3a83ea",
        "on-surface": "#1a1c1d",
        "inverse-surface": "#2f3132",
        background: "#f9f9fb",
        error: "#ba1a1a",
        "secondary-fixed": "#ffdbcd",
        "on-secondary-fixed": "#360f00",
        tertiary: "#000000",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadc",
        "surface-variant": "#e2e2e4",
        "on-surface-variant": "#4c4546",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#00458e",
        "on-background": "#1a1c1d",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#7e7576",
        "surface-bright": "#f9f9fb",
        "on-primary-fixed-variant": "#474747",
        "primary-container": "#1b1b1b",
        "accent-orange": "#eb4511",
        "burnt-orange": "#b02e0c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "32px",
        "container-max": "1440px",
        unit: "8px",
        "section-gap": "160px",
        "margin-edge": "64px",
      },
      fontFamily: {
        "headline-lg": ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "body-md":     ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "display-xl":  ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "display-2xl": ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "body-lg":     ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "headline-md": ["'Source Serif 4'", "'Source Serif Pro'", "Georgia", "serif"],
        "label-sm":    ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "48px",
          { lineHeight: "120%", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "160%", letterSpacing: "0em", fontWeight: "200" },
        ],
        "display-xl": [
          "80px",
          { lineHeight: "100%", letterSpacing: "-0.05em", fontWeight: "800" },
        ],
        "display-2xl": [
          "180px",
          { lineHeight: "90%", letterSpacing: "-0.06em", fontWeight: "800" },
        ],
        "body-lg": [
          "24px",
          { lineHeight: "150%", letterSpacing: "-0.01em", fontWeight: "200" },
        ],
        "headline-md": [
          "40px",
          { lineHeight: "120%", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "700" },
        ],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
  
};
